export const GET_PLAYER_RATING_HISTORY_REQUEST =
  "GET_PLAYER_RATING_HISTORY_REQUEST";
export const GET_PLAYER_RATING_HISTORY_SUCCESS =
  "GET_PLAYER_RATING_HISTORY_SUCCESS";
export const GET_PLAYER_RATING_HISTORY_FAILURE =
  "GET_PLAYER_RATING_HISTORY_FAILURE";

export const SET_PLAYER_RATING_HISTORY_TO_INITIAL =
  "SET_PLAYER_RATING_HISTORY_TO_INITIAL";

export const DOWNLOAD_RATING_HISTORY_REQUEST =
  "DOWNLOAD_RATING_HISTORY_REQUEST";
export const DOWNLOAD_RATING_HISTORY_SUCCESS =
  "DOWNLOAD_RATING_HISTORY_SUCCESS";
export const DOWNLOAD_RATING_HISTORY_FAILURE =
  "DOWNLOAD_RATING_HISTORY_FAILURE";
